export enum RouterMain {
  MAIN = 'Main',
  HOME = 'Home',
  NEWS = 'News',
  NEWS_PARAMS = 'News/:id',
  DISTRICT_NEWS = 'District-news',
  DISTRICT_NEWS_PARAMS = 'District-news/:id',
  APPEAL = 'Appeal',
  CONTACTS = 'Contacts',
  CONTACTS_PARAMS = 'Contacts/:id',
  DISPATCHER = 'Dispatcher',
  PERSONAL_CABINET = 'Personal-cabinet',
  PERSONAL_CABINET_LIST_ORDERS = 'List-orders',
  ORDER_PARAMS = 'Order/:id',
  ADMIN = 'Admin',
}
